### ISSUE TITLE
Need better x-axis label formatting.

### ISSUE THREAD

**Issue by constellates** [n3-charts/line-chart#121]
I'm not sure if I'm missing an option but I am struggling to get useable x-axis labels. It appears that no matter what my input data set is, I always have 13 labels on the x-axis. I'm running into an issue when the labels are rather large (large numbers like 4400), they overlap one another if their isn't enough space (making them unreadable. I would also like the option to only use the first and last x-axis label or at least know from my labelFunction if the input is the first or last value. Let me know if anything like this is in your roadmap or if I've missed or misused existing features.

**Comment by disquizzed** [comment]
I have a similar problem, but having less ticks is not a solution for me since my labelFunction returns Strings which I always need to have displayed under the columns in my charts. And since I have many columns in my charts, this automatically means that my Ox labels overlap.

Is there any recommended workaround or solution available in order to have my Ox label Strings visible and not overlapping?

I have a hack in mind, that is rotating the labels on the Ox axis by overriding the default CSS. However, I would prefer a cleaner solution if available and also, considering this hack, I would not be quite happy with the way the chart would look in charts with less columns for which no actual Ox axis label rotation would be needed.
