### ISSUE TITLE
No Axis Titles

### ISSUE THREAD

**Issue by jahumes** [n3-charts/line-chart#174]
We have a client who is needing to have axis titles, but there doesn't seem to be an easy way to accomplish axis titles.

**Comment by ParAnton** [comment]
We also need that, any suggestion of how to achieve it with todays version?

**Comment by andyunleashed** [comment]
You can also use CSS for this - had the same problem myself.

I added a container for the chart and then used before & after psuedo elements that were absolutely positioned.

Example code (I use SCSS, so take that into account if using plain CSS);

    .chart-container {
        position: relative;
        height: 400px;
        margin: $gap 0 0 0;
        padding: 0 0 0 5px;
        &:before {
            opacity: 0.5;
            content: "TIDE\A(M)"; // \A = line break
            position: absolute;
            top: 50%;
            left: 5px;
            @include transform(translateY(-50%));
            color: $blueText;
            @include font-size(10);
            white-space:pre;
            text-align: center;
            line-height: 1.1;
        }
        &:after {
            opacity: 0.5;
            content: "HOUR OF THE DAY";
            position: absolute;
            bottom: 0;
            left: 50%;
            @include transform(translateY(-55%));
            color: $blueText;
            @include font-size(10);
            text-align: center;
        }
    }

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
