### ISSUE TITLE
thumbnail tooltip

### ISSUE THREAD

**Issue by cscrum** [n3-charts/line-chart#175]
Is there any chance of getting tooltips on the thumbnails?

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
