### ISSUE TITLE
left / right tooltip opening control

### ISSUE THREAD

**Issue by MaciejBaj** [n3-charts/line-chart#265]
Is it possible to control which tooltip will open (left or right side) when point hovers? On attached image tooltip content is completely invisible.

![unvisible chart tooltip](https://cloud.githubusercontent.com/assets/6909553/8327531/76901e02-1a69-11e5-98da-e80e48bc8955.PNG)

**Comment by chaosmail** [comment]
Hi @MaciejBaj 

the tooltips should chage the position automatically to be displayed properly. Your behavior seems to be a bug, maybe when using text labels. Can you post a plunkr to reproduce this behavior?

You could temporarily add a `margin: { right: 100 }` option to the chart, to create some more space on the right side.

Best,
Christoph

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
