### ISSUE TITLE
error when data miss a field

### ISSUE THREAD

**Issue by truyen93** [n3-charts/line-chart#322]
hi, 
I'm working with your chart and I got some error when my data miss data for line.
So can I fix it? thank!

http://plnkr.co/edit/nnxSe7st36Kyqil5RqN6?p=preview

**Comment by chaosmail** [comment]
Hi @truyen93 
so you are defining a key for a series that is not existing in the data set. I agree, that the current behavior is a bit weird because the scrubber throws some strange errors. However, I think that in a proper solution we should still throw a `KeyError` or something to indicate that there has been an error.

In your case, you could have a workaround and define a default value for this key on the data set. Here is an example: http://plnkr.co/edit/o7DMRCMcaO36Y5H0Yvjx?p=preview

Let me know if this is an acceptable workaround for you!

Best,
Christoph

**Comment by truyen93** [comment]
hi @chaosmail, 
my data's field is dynamic, in some case it does not defined. I fixed that error by add lines or colume when this field defined.

Thank you so much!

**Comment by chaosmail** [comment]
ok I see; yeah we never really thought about this, maybe we could hide the series automatically if the key is not found

**Comment by chaosmail** [comment]
alright, glad this is working for you
