### ISSUE TITLE
$rootScope:infdig error in FF 31

### ISSUE THREAD

**Issue by bertomaniac** [n3-charts/line-chart#372]
This error appears in FF 31 and could appear in older browsers as well. I tracked it down to how the options are being built/sanitized.  I believe there needs to be an `angular.copy(options)` before the options get passed in to be sanitized.  At the moment, changing the `options` object in place within `sanitizeOptions()` triggers additional $watchers to fire.

Should be easy enough to add `options = angular.copy(scope.options)` and then pass this into `_u.sanitizeOptions(options, attrs.mode)`

**Comment by budcribar** [comment]
I had the same problem when I had a chart in a ng-repeat loop.  Changing 
options = _u.sanitizeOptions(scope.options, attrs.mode) to 
options = _u.sanitizeOptions(angular.copy(scope.options), attrs.mode) 
fixed it. Many thanks bertomaniac :)

**Comment by pihomeserver** [comment]
+1 ! Helped me to fix my errors in Chrome and FF (not in Safari)

Thx @bertomaniac !

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
