### ISSUE TITLE
Series without data breaks chart

### ISSUE THREAD

**Issue by QualifiedSuccess** [n3-charts/line-chart#374]
Hi,

if you got a series defined and no field in the data it breaks your whole chart. Means all other series are not drawn anymore.

See: http://codepen.io/anon/pen/vNQyKX
If you enable "Series without data" by clicking on the legend it breaks the chart.

I cannot remove the series in my case because I need the legend label.

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
