### ISSUE TITLE
Add event handlers to drawArea, add mousemove event

### ISSUE THREAD

**Issue by frankfralick** [n3-charts/line-chart#377]
I have added some features that I would like to create a pull request for if it seems like something that would be useful.  

The specific use case that I have is a stacked area series that can contain more series than it makes sense to create a legend for.  The user hovers over an area and a popover follows the mouse around and the popover changes based on the area below.  They can click in the area that is of interest and they are taken to more detail.   Here is a screenshot:

![area chart](https://cloud.githubusercontent.com/assets/2084232/11282330/c5100038-8ecc-11e5-9c2e-0fb6c819fe4e.png)

Doing this requires adding the mousemove event, and adding the click and mouse events to drawArea.  If this makes sense to add I can add tests/example and create a pull request.

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
