### ISSUE TITLE
Scrubber function

### ISSUE THREAD

**Issue by Maikor** [n3-charts/line-chart#380]
Hello!

For example I have 3 series. Is it possible to display tooltip only for 2 of them?

**Comment by lorem--ipsum** [comment]
Hmmmm I don't think it's possible currently...

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
