### ISSUE TITLE
How to set ticksInterval for integer values?

### ISSUE THREAD

**Issue by nishadotcom** [n3-charts/line-chart#382]
Hai All!

How to set ticksInterval value for min: 50, max: 500 ????

Best,
nishadotcom

**Comment by lorem--ipsum** [comment]
Hi, are you trying to set the min/max for an axis ?

**Comment by nishadotcom** [comment]
Hai @lorem--ipsum 

I have set min=0 and max=500. I want the Y axis interval to be 100.

Ex 
500

400

300

200

100

0

Note:
I did this by setting ticks=5.

Best,
nishadotcom

**Comment by chaosmail** [comment]
Hi @nishadotcom 
is this still an issue or can I close it?
Best,
Christoph

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
