### ISSUE TITLE
n3 line chart only in single value

### ISSUE THREAD

**Issue by padmarao123** [n3-charts/line-chart#383]
In graph only in single value x-axis values become so far

eg: yerar in axis 500 1000 3000 4000 ...
but year is present 2015 like that

**Comment by lorem--ipsum** [comment]
Hi, could you be more specific ? Not sure I'm getting what you mean...

Thanks !

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
