### ISSUE TITLE
Localization of date axis labels

### ISSUE THREAD

**Issue by nicolasr75** [n3-charts/line-chart#501]
First of all: this is an awesome component! I have been so impressed by how many things just work beautifully with n3-charts! :-)
What I couldn't find information about though, or don't understand, is:
how can I localize the labeling on date axes? I am on a german system and would like to have the german month abbreviations.

**Comment by chaosmail** [comment]
Hi @nicolasr75 
check out this example using D3 time format and german locale: http://codepen.io/chaosmail/pen/VaNQJG
We are using D3, so you can use all time formatters available in D3 (https://github.com/d3/d3/wiki/Time-Formatting).

If you look closely in the example, i am using `germanFormatters.timeFormat` for german locale instead of `d3.time.format`

```
var germanFormatters = d3.locale({
  "decimal": ",",
  "thousands": ".",
  "grouping": [3],
  "currency": ["€", ""],
  "dateTime": "%a %b %e %X %Y",
  "date": "%d.%m.%Y",
  "time": "%H:%M:%S",
  "periods": ["AM", "PM"],
  "days": ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
  "shortDays": ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
  "months": ["Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
  "shortMonths": ["Jän", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Dez"]
});
```

Best,
Christoph

**Comment by nicolasr75** [comment]
Thanks Christoph! I wasn't aware that the localized formatting is already part of D3, thanks for the example and the link. 
Nicolas.
